package nikguscode.com.crmbot.model.service.enums;

public enum TelegramType {
    TEXT, COMMAND, PHOTO, VIDEO, VOICE, ANIMATION, DOCUMENT, STICKER, AUDIO, CALLBACK,
    CONTACT, LOCATION, ENTITIES, POLL_WITH_TEXT, DICE, POLL, CHANNEL_POST, CHAT_MEMBER,
    SUCCESSFUL_PAYMENT, INVOICE, PRE_CHECKOUT_QUERY, PASSPORT_DATA, REPLY_MARKUP, VIA_BOT,
    VIDEO_NOTE, CHAT_JOIN_REQUEST, CHOOSE_INLINE_QUERY, EDITED_CHANNEL_POST, EDITED_MESSAGE,
    INLINE_QUERY, POLL_ANSWER, SHIPPING_QUERY, UNKNOWN_UPDATE, UNKNOWN_MESSAGE, SYSTEM;
}
